apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-charts.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  JWT_SECRET_KEY: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMDA4MTcxNywiaWF0IjoxNzIwMDgxNzE3fQ.pVVn3P7Fzl62b6O-Qge0TpUiA75zu1rNGXpzwykkRHc"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
