apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-charts.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "my-charts.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc }}
