stages:
  - lint
  - test
  - build

build:
  stage: build
  image: shift_face_verification_devcontainer-app:latest
  script:
    - poetry shell
    - poetry install
    - poetry run python src/app/main.py

test:
  stage: test
  image: shift_face_verification_devcontainer-app:latest
  script:
    - poetry shell
    - poetry install
    - poetry run pytest

lint:
  stage: lint
  image: shift_face_verification_devcontainer-app:latest
  script:
    - poetry shell
    - poetry install
    - "poetry run isort src/app"
    - poetry run flake8 --jobs=1 src/app
  allow_failure: true
