apiVersion: apps/v1
kind: Deployment
metadata:
  name: zar-face-verification-service
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zar-face-verification-service
  template:
    metadata:
      labels:
        app: zar-face-verification-service
    spec:
      containers:
      - name: zar-face-verification-service
        image: aliquis21/face-verification-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: face-verification-service-secrets
              key: DATABASE_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: face-verification-service-config
              key: KAFKA_BOOTSTRAP_SERVERS
