version: '3'

services:
  app:
    container_name: 'shift-python-2024-base'
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - '28080:8080'
    command: '/bin/sh -c "while sleep 1000; do :; done"'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
